services:
  db:
    image: postgis/postgis:16-3.4
    container_name: archelp_db
    environment:
      POSTGRES_DB: archelp
      POSTGRES_USER: archelp
      POSTGRES_PASSWORD: archelp_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
