# Generated by Django 6.1.1 on 2026-09-04 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('type_piece', models.CharField(choices=[('REGLEMENT', 'Règlement écrit'), ('OAP', "Orientations d'Aménagement et de Programmation"), ('RAPPORT', 'Rapport de présentation'), ('ANNEXE', 'Annexe'), ('PADD', "Projet d'Aménagement et de Développement Durables"), ('AUTRE', 'Autre')], db_index=True, default='REGLEMENT', max_length=20)),
                ('url_source', models.URLField(help_text="URL d'origine du PDF", max_length=1000)),
                ('fichier', models.FileField(blank=True, help_text='Copie locale du PDF', upload_to='reglements/%Y/%m/')),
                ('sha256', models.CharField(blank=True, db_index=True, help_text='Empreinte du fichier, pour détecter les mises à jour', max_length=64)),
                ('taille_octets', models.BigIntegerField(blank=True, null=True)),
                ('nb_pages', models.IntegerField(blank=True, null=True)),
                ('date_document', models.DateField(blank=True, help_text="Date d'approbation ou de mise à jour du règlement. À citer obligatoirement dans toute réponse à l'utilisateur.", null=True)),
                ('statut', models.CharField(choices=[('A_TELECHARGER', 'À télécharger'), ('TELECHARGE', 'Téléchargé'), ('TEXTE_EXTRAIT', 'Texte extrait'), ('ERREUR', 'Erreur')], db_index=True, default='A_TELECHARGER', max_length=20)),
                ('message_erreur', models.TextField(blank=True)),
                ('est_numerise', models.BooleanField(blank=True, help_text='Vrai si PDF scanné sans couche texte (OCR nécessaire)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telecharge_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='parcels.documenturbanisme')),
            ],
            options={
                'verbose_name': 'Règlement (PDF)',
                'verbose_name_plural': 'Règlements (PDF)',
                'ordering': ['document', 'type_piece', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='ReglementSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(help_text="Position dans le document, pour restituer l'ordre de lecture")),
                ('page_debut', models.IntegerField(blank=True, null=True)),
                ('page_fin', models.IntegerField(blank=True, null=True)),
                ('titre', models.CharField(blank=True, help_text='Ex: Article UB 10 - Hauteur maximale des constructions', max_length=500)),
                ('numero_article', models.CharField(blank=True, db_index=True, help_text="Ex: UB 10, ou 'UB-4.2' pour un PLU post-2015", max_length=50)),
                ('texte', models.TextField()),
                ('nb_caracteres', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='urbanism_docs.reglementdocument')),
                ('zone', models.ForeignKey(blank=True, help_text='Zone concernée, si la section est rattachable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='parcels.zone')),
            ],
            options={
                'verbose_name': 'Section de règlement',
                'verbose_name_plural': 'Sections de règlement',
                'ordering': ['reglement', 'ordre'],
            },
        ),
        migrations.AddIndex(
            model_name='reglementdocument',
            index=models.Index(fields=['document', 'statut'], name='urbanism_do_documen_5271ab_idx'),
        ),
        migrations.AddIndex(
            model_name='reglementsection',
            index=models.Index(fields=['zone', 'numero_article'], name='urbanism_do_zone_id_9de76c_idx'),
        ),
        migrations.AddConstraint(
            model_name='reglementsection',
            constraint=models.UniqueConstraint(fields=('reglement', 'ordre'), name='unique_section_par_reglement'),
        ),
    ]
