# Generated by Django 6.1.1 on 2026-09-04 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcelle_code_arrondissement_parcelle_feuille_and_more'),
        ('urbanism_docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reglementsection',
            options={'ordering': ['reglement', 'chemin'], 'verbose_name': 'Fragment de règlement (SRU niveau 1)', 'verbose_name_plural': 'Fragments de règlement (SRU niveau 1)'},
        ),
        migrations.RemoveConstraint(
            model_name='reglementsection',
            name='unique_section_par_reglement',
        ),
        migrations.RemoveIndex(
            model_name='reglementsection',
            name='urbanism_do_zone_id_9de76c_idx',
        ),
        migrations.AddField(
            model_name='reglementsection',
            name='chemin',
            field=models.CharField(blank=True, db_index=True, help_text='Chemin matérialisé, ex: 0002.0005.0001 — pour trier et retrouver une sous-arborescence en une requête', max_length=200),
        ),
        migrations.AddField(
            model_name='reglementsection',
            name='numero',
            field=models.CharField(blank=True, db_index=True, help_text='Ex: UB 10, ou UB-4.2 pour un PLU post-2015', max_length=50),
        ),
        migrations.AddField(
            model_name='reglementsection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='urbanism_docs.reglementsection'),
        ),
        migrations.AddField(
            model_name='reglementsection',
            name='profondeur',
            field=models.IntegerField(default=0, help_text="Niveau dans l'arbre, 0 pour la racine"),
        ),
        migrations.AddField(
            model_name='reglementsection',
            name='renvois',
            field=models.ManyToManyField(blank=True, help_text='Articles cités par ce fragment', related_name='cite_par', to='urbanism_docs.reglementsection'),
        ),
        migrations.AddField(
            model_name='reglementsection',
            name='type_fragment',
            field=models.CharField(choices=[('TITRE', 'Titre'), ('SOUS_TITRE', 'Sous-titre'), ('CHAPITRE', 'Chapitre'), ('SECTION', 'Section'), ('ARTICLE', 'Article'), ('PARAGRAPHE', 'Paragraphe'), ('ALINEA', 'Alinéa'), ('ILLUSTRATION', 'Schéma ou illustration')], db_index=True, default='ARTICLE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglementsection',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text='Zones concernées. Un même chapitre couvre souvent plusieurs zones (A1 à A5 partagent la page 177).', related_name='sections', to='parcels.zone'),
        ),
        migrations.AlterField(
            model_name='reglementsection',
            name='ordre',
            field=models.IntegerField(help_text='Rang parmi les frères'),
        ),
        migrations.AlterField(
            model_name='reglementsection',
            name='texte',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reglementsection',
            name='titre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='reglementsection',
            index=models.Index(fields=['reglement', 'chemin'], name='urbanism_do_regleme_0c1061_idx'),
        ),
        migrations.AddIndex(
            model_name='reglementsection',
            index=models.Index(fields=['reglement', 'type_fragment'], name='urbanism_do_regleme_1c2325_idx'),
        ),
        migrations.RemoveField(
            model_name='reglementsection',
            name='numero_article',
        ),
        migrations.RemoveField(
            model_name='reglementsection',
            name='zone',
        ),
    ]
