# Generated by Django 6.1.1 on 2026-09-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanism_docs', '0002_alter_reglementsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglementdocument',
            name='statut',
            field=models.CharField(choices=[('A_TELECHARGER', 'À télécharger'), ('TELECHARGE', 'Téléchargé'), ('TEXTE_EXTRAIT', 'Texte brut extrait'), ('STRUCTURE_N1', 'Structuré SRU niveau 1'), ('REGLES_N2', 'Règles extraites SRU niveau 2'), ('ERREUR', 'Erreur')], db_index=True, default='A_TELECHARGER', max_length=20),
        ),
    ]
