# Generated by Django 6.1.1 on 2026-09-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanism_docs', '0003_alter_reglementdocument_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglementdocument',
            name='chemin_interne',
            field=models.CharField(blank=True, help_text="Chemin du fichier dans l'archive ZIP du GPU", max_length=500),
        ),
    ]
