# Generated by Django 6.1.1 on 2026-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanism_docs', '0004_reglementdocument_chemin_interne'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglementdocument',
            name='extraction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reglementdocument',
            name='extraction_brute',
            field=models.JSONField(blank=True, help_text="Fragments renvoyés par le modèle, avant construction de l'arborescence. Conservé pour rejouer l'assemblage sans rappeler le modèle.", null=True),
        ),
        migrations.AddField(
            model_name='reglementdocument',
            name='extraction_modele',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
