# Generated by Django 6.1.1 on 2026-09-22 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_zone_chapitre_at_zone_page_chapitre_debut_and_more'),
        ('urbanism_docs', '0005_reglementdocument_extraction_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionChapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(help_text="Empreinte du PDF et plage de pages : un chapitre partagé n'est payé qu'une fois", max_length=400, unique=True)),
                ('page_debut', models.IntegerField()),
                ('page_fin', models.IntegerField()),
                ('zones_attendues', models.JSONField(default=list)),
                ('zones_lues', models.JSONField(default=list)),
                ('regles', models.JSONField(default=list)),
                ('brut', models.TextField(blank=True, help_text='Texte brut de la réponse')),
                ('modele', models.CharField(max_length=60)),
                ('niveau', models.CharField(help_text='Niveau de réflexion de la réponse retenue', max_length=10)),
                ('version_prompt', models.CharField(max_length=20)),
                ('couverture', models.FloatField(blank=True, null=True)),
                ('nb_nombres', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('OK', 'Retenue'), ('A_REPRENDRE', 'Couverture insuffisante, à reprendre en niveau high'), ('ZONE_REJETEE', 'Le chapitre ne traite pas de la zone attendue'), ('JSON_INVALIDE', 'Réponse inexploitable'), ('TRONQUE', 'Réponse tronquée'), ('ERREUR', "Échec d'appel")], db_index=True, max_length=20)),
                ('jetons_entree', models.IntegerField(default=0, help_text='Cumul de tous les passages')),
                ('jetons_sortie', models.IntegerField(default=0, help_text='Réponse et réflexion, cumul')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='urbanism_docs.reglementdocument')),
                ('zones', models.ManyToManyField(blank=True, related_name='extractions', to='parcels.zone')),
            ],
            options={
                'verbose_name': 'Extraction de chapitre',
                'verbose_name_plural': 'Extractions de chapitres',
                'ordering': ['reglement', 'page_debut'],
            },
        ),
    ]
