# Generated by Django 6.1.1 on 2026-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanism_docs', '0006_extractionchapitre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionchapitre',
            name='statut',
            field=models.CharField(choices=[('OK', 'Retenue'), ('A_REPRENDRE', 'Couverture insuffisante, à reprendre en niveau high'), ('ZONE_REJETEE', 'Le chapitre ne traite pas de la zone attendue'), ('JSON_INVALIDE', 'Réponse inexploitable'), ('TRONQUE', 'Réponse tronquée'), ('ERREUR', "Échec d'appel"), ('VIDE', 'Aucune règle relevée')], db_index=True, max_length=20),
        ),
    ]
