# Generated by Django 6.1.1 on 2026-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanism_docs', '0007_alter_extractionchapitre_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_job', models.CharField(max_length=200, unique=True)),
                ('niveau', models.CharField(max_length=10)),
                ('version_prompt', models.CharField(max_length=20)),
                ('chapitres', models.JSONField()),
                ('etat', models.CharField(choices=[('SOUMIS', 'Soumis, en attente'), ('TERMINE', 'Réponses enregistrées'), ('ECHEC', 'Échec, chapitres à resoumettre')], db_index=True, default='SOUMIS', max_length=10)),
                ('etat_api', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('termine_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
