# Generated by Django 6.1.1 on 2026-09-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanism_docs', '0008_lotbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionchapitre',
            name='renvois',
            field=models.JSONField(default=list, help_text='Passages renvoyant à des règles situées hors du chapitre'),
        ),
    ]
