# Generated by Django 6.1.1 on 2026-09-22 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_zone_chapitre_at_zone_page_chapitre_debut_and_more'),
        ('urbanism_docs', '0009_extractionchapitre_renvois'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.CharField(db_index=True, max_length=20)),
                ('theme', models.CharField(max_length=40)),
                ('valeur', models.CharField(blank=True, max_length=300)),
                ('condition', models.CharField(blank=True, max_length=500)),
                ('citation', models.TextField(blank=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('a_valeur', models.BooleanField(db_index=True, default=False)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'apparition dans le texte")),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_zone', to='urbanism_docs.extractionchapitre')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='parcels.zone')),
            ],
            options={
                'verbose_name': 'Règle de zone',
                'verbose_name_plural': 'Règles de zone',
                'ordering': ['zone', 'ordre'],
                'indexes': [models.Index(fields=['zone', 'groupe'], name='urbanism_do_zone_id_ed1b8a_idx')],
            },
        ),
    ]
