# Generated by Django 6.1.1 on 2026-09-04 13:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_insee', models.CharField(db_index=True, help_text='Code INSEE sur 5 caractères, ex: 67482 (Strasbourg)', max_length=5, unique=True)),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('code_postal', models.CharField(blank=True, max_length=5)),
                ('code_departement', models.CharField(db_index=True, help_text='Ex: 67, 68, 2A', max_length=3)),
                ('code_region', models.CharField(db_index=True, help_text='Ex: 44 pour Grand Est', max_length=2)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('surface_ha', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Limites administratives, WGS84', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='Dernière synchronisation depuis la source officielle', null=True)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['code_insee'],
                'indexes': [models.Index(fields=['code_region', 'code_departement'], name='parcels_com_code_re_fdcce0_idx')],
            },
        ),
    ]
