# Generated by Django 6.1.1 on 2026-09-04 13:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_insee', models.CharField(db_index=True, help_text='Code INSEE sur 5 caractères, ex: 67482 (Strasbourg)', max_length=5, unique=True)),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('code_postal', models.CharField(blank=True, max_length=5)),
                ('code_departement', models.CharField(db_index=True, help_text='Ex: 67, 68, 2A', max_length=3)),
                ('code_region', models.CharField(db_index=True, help_text='Ex: 44 pour Grand Est', max_length=2)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('surface_ha', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Limites administratives, WGS84', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='Dernière synchronisation depuis la source officielle', null=True)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['code_insee'],
                'indexes': [models.Index(fields=['code_region', 'code_departement'], name='parcels_com_code_re_fdcce0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentUrbanisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.CharField(db_index=True, help_text='Identifiant GPU de partition, ex: DU_67482. Non unique.', max_length=32)),
                ('idurba', models.CharField(db_index=True, help_text='Identifiant CNIG du document, ex: 67482_PLU_20200115', max_length=30)),
                ('type_document', models.CharField(choices=[('PLU', "Plan Local d'Urbanisme"), ('PLUI', "Plan Local d'Urbanisme intercommunal"), ('POS', "Plan d'Occupation des Sols"), ('CC', 'Carte Communale'), ('PSMV', 'Plan de Sauvegarde et de Mise en Valeur'), ('RNU', "Règlement National d'Urbanisme")], max_length=10)),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('date_fin_validite', models.DateField(blank=True, null=True)),
                ('est_en_vigueur', models.BooleanField(db_index=True, default=True)),
                ('nom_procedure', models.CharField(blank=True, help_text='Code CNIG de la procédure : R (révision), M1 (modification), MS1...', max_length=10)),
                ('nom_reglement', models.CharField(blank=True, max_length=200)),
                ('url_reglement', models.URLField(blank=True, max_length=500)),
                ('url_plan', models.URLField(blank=True, max_length=500)),
                ('site_web', models.URLField(blank=True, max_length=500)),
                ('a_doublon_source', models.BooleanField(db_index=True, default=False, help_text='Vrai si la source contenait plusieurs lignes opposables pour cette partition. Réponse à vérifier auprès de la mairie.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('communes', models.ManyToManyField(help_text='Plusieurs communes si PLUi', related_name='documents_urbanisme', to='parcels.commune')),
            ],
            options={
                'verbose_name': "Document d'urbanisme",
                'verbose_name_plural': "Documents d'urbanisme",
                'ordering': ['-date_approbation'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idu', models.CharField(db_index=True, help_text='Identifiant unique: code_insee + prefixe(3) + section(2) + numero(4). Ex: 674820000AB0123', max_length=14, unique=True)),
                ('prefixe', models.CharField(default='000', help_text='Préfixe, non nul si commune fusionnée', max_length=3)),
                ('section', models.CharField(help_text='Ex: AB', max_length=2)),
                ('numero', models.CharField(help_text='Ex: 0123', max_length=4)),
                ('contenance_m2', models.IntegerField(blank=True, help_text='Surface cadastrale déclarée, en m²', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelles', to='parcels.commune')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['idu'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_index=True, help_text='Libellé exact du PLU, ex: UB2, UAa, 1AU, Nzh', max_length=50)),
                ('libelle_long', models.CharField(blank=True, max_length=500)),
                ('type_zone', models.CharField(choices=[('U', 'Zone urbaine'), ('AU', 'Zone à urbaniser'), ('A', 'Zone agricole'), ('N', 'Zone naturelle et forestière'), ('AUc', 'Zone à urbaniser constructible'), ('AUs', 'Zone à urbaniser stricte'), ('AUTRE', 'Autre / non normalisé')], db_index=True, help_text='Type normalisé CNIG, déduit du libellé', max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='parcels.documenturbanisme')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['document', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ParcelleZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_intersection_m2', models.FloatField(help_text='Surface de la parcelle dans cette zone, en m² (calculée en Lambert-93)')),
                ('part_pct', models.FloatField(help_text='Part de la parcelle dans cette zone, en %')),
                ('est_dominante', models.BooleanField(db_index=True, default=False, help_text='Vrai pour la zone couvrant la plus grande part')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcelle')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.zone')),
            ],
            options={
                'verbose_name': 'Parcelle × Zone',
                'verbose_name_plural': 'Parcelles × Zones',
                'ordering': ['-part_pct'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='parcelles', through='parcels.ParcelleZone', to='parcels.zone'),
        ),
        migrations.AddConstraint(
            model_name='documenturbanisme',
            constraint=models.UniqueConstraint(fields=('partition', 'idurba'), name='unique_partition_idurba'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('document', 'libelle'), name='unique_zone_par_document'),
        ),
        migrations.AddConstraint(
            model_name='parcellezone',
            constraint=models.UniqueConstraint(fields=('parcelle', 'zone'), name='unique_parcelle_zone'),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['commune', 'section', 'numero'], name='parcels_par_commune_23767a_idx'),
        ),
    ]
