# Generated by Django 6.1.1 on 2026-09-04 13:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUrbanisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.CharField(db_index=True, help_text='Identifiant GPU, ex: DU_67482. Clé de rattachement du zonage.', max_length=50, unique=True)),
                ('type_document', models.CharField(choices=[('PLU', "Plan Local d'Urbanisme"), ('PLUi', "Plan Local d'Urbanisme intercommunal"), ('POS', "Plan d'Occupation des Sols"), ('CC', 'Carte Communale'), ('PSMV', 'Plan de Sauvegarde et de Mise en Valeur'), ('RNU', "Règlement National d'Urbanisme")], max_length=10)),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('date_fin_validite', models.DateField(blank=True, null=True)),
                ('est_en_vigueur', models.BooleanField(db_index=True, default=True)),
                ('url_gpu', models.URLField(blank=True, help_text='Fiche sur geoportail-urbanisme.gouv.fr', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('communes', models.ManyToManyField(help_text='Plusieurs communes si PLUi', related_name='documents_urbanisme', to='parcels.commune')),
            ],
            options={
                'verbose_name': "Document d'urbanisme",
                'verbose_name_plural': "Documents d'urbanisme",
                'ordering': ['-date_approbation'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_index=True, help_text='Libellé exact du PLU, ex: UB2, UAa, 1AU, Nzh', max_length=50)),
                ('libelle_long', models.CharField(blank=True, max_length=500)),
                ('type_zone', models.CharField(choices=[('U', 'Zone urbaine'), ('AU', 'Zone à urbaniser'), ('A', 'Zone agricole'), ('N', 'Zone naturelle et forestière'), ('AUc', 'Zone à urbaniser constructible'), ('AUs', 'Zone à urbaniser stricte'), ('AUTRE', 'Autre / non normalisé')], db_index=True, help_text='Type normalisé CNIG, déduit du libellé', max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='parcels.documenturbanisme')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['document', 'libelle'],
                'constraints': [models.UniqueConstraint(fields=('document', 'libelle'), name='unique_zone_par_document')],
            },
        ),
    ]
