# Generated by Django 6.1.1 on 2026-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='nb_polygones',
            field=models.IntegerField(default=1, help_text='Nombre de polygones fusionnés sous ce libellé'),
        ),
        migrations.AddField(
            model_name='zone',
            name='nom_fichier_reglement',
            field=models.CharField(blank=True, help_text='Champ nomfic du GPU, ex: 246700488_reglement_20260206.pdf#page=95', max_length=300),
        ),
        migrations.AddField(
            model_name='zone',
            name='page_reglement',
            field=models.IntegerField(blank=True, help_text="Page extraite de nomfic. Point d'entrée dans le PDF.", null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='libelle',
            field=models.CharField(db_index=True, help_text='Libellé exact du PLU, ex: UD1, IAUB, Nzh', max_length=50),
        ),
        migrations.AlterField(
            model_name='zone',
            name='type_zone',
            field=models.CharField(choices=[('U', 'Zone urbaine'), ('AU', 'Zone à urbaniser'), ('AUc', 'Zone à urbaniser constructible'), ('AUs', 'Zone à urbaniser stricte'), ('A', 'Zone agricole'), ('N', 'Zone naturelle et forestière'), ('AUTRE', 'Autre / non normalisé')], db_index=True, help_text="Type normalisé CNIG, champ typezone de l'API", max_length=10),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['type_zone', 'libelle'], name='parcels_zon_type_zo_b579f2_idx'),
        ),
    ]
