# Generated by Django 6.1.1 on 2026-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_zone_nb_polygones_zone_nom_fichier_reglement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='type_zone',
            field=models.CharField(choices=[('U', 'Zone urbaine'), ('AU', 'Zone à urbaniser'), ('AUc', 'Zone à urbaniser constructible'), ('AUs', 'Zone à urbaniser stricte'), ('A', 'Zone agricole'), ('N', 'Zone naturelle et forestière'), ('CC01', 'CC — ouvert à la construction'), ('CC02', 'CC — réservé aux activités'), ('CC03', 'CC — fermé à la construction'), ('CC99', 'CC — non couvert par la carte'), ('AUTRE', 'Autre / non normalisé')], db_index=True, help_text="Type normalisé CNIG, champ typezone de l'API", max_length=10),
        ),
    ]
