# Generated by Django 6.1.1 on 2026-09-04 13:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_documenturbanisme_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idu', models.CharField(db_index=True, help_text='Identifiant unique: code_insee + prefixe(3) + section(2) + numero(4). Ex: 674820000AB0123', max_length=14, unique=True)),
                ('prefixe', models.CharField(default='000', help_text='Préfixe, non nul si commune fusionnée', max_length=3)),
                ('section', models.CharField(help_text='Ex: AB', max_length=2)),
                ('numero', models.CharField(help_text='Ex: 0123', max_length=4)),
                ('contenance_m2', models.IntegerField(blank=True, help_text='Surface cadastrale déclarée, en m²', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelles', to='parcels.commune')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['idu'],
            },
        ),
        migrations.CreateModel(
            name='ParcelleZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_intersection_m2', models.FloatField(help_text='Surface de la parcelle dans cette zone, en m² (calculée en Lambert-93)')),
                ('part_pct', models.FloatField(help_text='Part de la parcelle dans cette zone, en %')),
                ('est_dominante', models.BooleanField(db_index=True, default=False, help_text='Vrai pour la zone couvrant la plus grande part')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcelle')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.zone')),
            ],
            options={
                'verbose_name': 'Parcelle × Zone',
                'verbose_name_plural': 'Parcelles × Zones',
                'ordering': ['-part_pct'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='parcelles', through='parcels.ParcelleZone', to='parcels.zone'),
        ),
        migrations.AddConstraint(
            model_name='parcellezone',
            constraint=models.UniqueConstraint(fields=('parcelle', 'zone'), name='unique_parcelle_zone'),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['commune', 'section', 'numero'], name='parcels_par_commune_23767a_idx'),
        ),
    ]
