# Generated by Django 6.1.1 on 2026-09-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_alter_zone_type_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='code_arrondissement',
            field=models.CharField(default='000', help_text='Code arrondissement, non nul à Paris/Lyon/Marseille', max_length=3),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='feuille',
            field=models.IntegerField(default=1, help_text='Numéro de feuille cadastrale'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='gid_ign',
            field=models.IntegerField(blank=True, help_text='Identifiant interne IGN, pour traçabilité', null=True),
        ),
    ]
