# Generated by Django 6.1.1 on 2026-09-09 11:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcelle_code_arrondissement_parcelle_feuille_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_ign', models.IntegerField(db_index=True)),
                ('type_psc', models.CharField(db_index=True, max_length=2)),
                ('stype_psc', models.CharField(blank=True, max_length=2)),
                ('libelle', models.CharField(db_index=True, max_length=300)),
                ('txt', models.CharField(blank=True, help_text='Valeur brute. Pour la hauteur : « 12mHT » (hors tout) ou « 10mET » (égout de toiture) — deux modes de mesure distincts.', max_length=200)),
                ('valeur_num', models.FloatField(blank=True, help_text='Valeur numérique extraite de txt, quand elle existe', null=True)),
                ('unite', models.CharField(blank=True, help_text='m, %, ou vide', max_length=10)),
                ('reference_mesure', models.CharField(blank=True, help_text='HT (hors tout) ou ET (égout de toiture) pour les hauteurs', max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='parcels.documenturbanisme')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['type_psc', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ParcellePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_intersection_m2', models.FloatField()),
                ('part_pct', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcelle')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.prescription')),
            ],
            options={
                'verbose_name': 'Parcelle × Prescription',
                'verbose_name_plural': 'Parcelles × Prescriptions',
                'ordering': ['-part_pct'],
            },
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('document', 'gid_ign'), name='unique_prescription_ign'),
        ),
        migrations.AddConstraint(
            model_name='parcelleprescription',
            constraint=models.UniqueConstraint(fields=('parcelle', 'prescription'), name='unique_parcelle_prescription'),
        ),
    ]
