# Generated by Django 6.1.1 on 2026-09-14 19:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_prescription_parcelleprescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.CharField(db_index=True, help_text='Partition propre à la SUP, ex: 172014607_SUP_67_AC1', max_length=64)),
                ('gid_ign', models.IntegerField(db_index=True)),
                ('sup_type', models.CharField(db_index=True, help_text='Code nomenclature, ex: AC1, PM1, I4', max_length=10)),
                ('id_assiette', models.CharField(blank=True, max_length=100)),
                ('id_generateur', models.CharField(blank=True, max_length=100)),
                ('nom_litteral', models.CharField(blank=True, help_text="Nom de l'élément protégé ou de l'ouvrage générateur", max_length=300)),
                ('type_assiette', models.CharField(blank=True, help_text='Ex: Périmètre des abords, Zone de protection', max_length=150)),
                ('mode_geometrie', models.CharField(blank=True, max_length=100)),
                ('parametre_calcul', models.FloatField(blank=True, help_text='Rayon de la zone tampon en mètres, le cas échéant', null=True)),
                ('fichier_acte', models.CharField(blank=True, help_text="Nom du PDF de l'acte instituant la servitude", max_length=300)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Servitude d'utilité publique",
                'verbose_name_plural': "Servitudes d'utilité publique",
                'ordering': ['sup_type', 'nom_litteral'],
                'constraints': [models.UniqueConstraint(fields=('partition', 'gid_ign'), name='unique_servitude_ign')],
            },
        ),
        migrations.CreateModel(
            name='ParcelleServitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_intersection_m2', models.FloatField()),
                ('part_pct', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcelle')),
                ('servitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.servitude')),
            ],
            options={
                'verbose_name': 'Parcelle × Servitude',
                'verbose_name_plural': 'Parcelles × Servitudes',
                'ordering': ['-part_pct'],
                'constraints': [models.UniqueConstraint(fields=('parcelle', 'servitude'), name='unique_parcelle_servitude')],
            },
        ),
    ]
