# Generated by Django 6.1.1 on 2026-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_servitude_parcelleservitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='chapitre_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='page_chapitre_debut',
            field=models.IntegerField(blank=True, help_text='Début du chapitre de la zone, repéré dans le corps du PDF', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='page_chapitre_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='type_chapitre',
            field=models.CharField(blank=True, help_text='exact/forte, secteur/forte… — fiabilité de la détection', max_length=20),
        ),
    ]
